organization: Team-jeong-ho-kim
repository: -Daedongyeojido_BE_v3.5
branch: main
containerPort: 8080
domain: daedongyeojido-server.xquare.app
language: java
criticalService: false
buildConfig: '{"builder":"gradle","jdk_version":17,"build_dir":"/","build_commands":["./gradlew build -x test"],"output_dir":"/build/libs/daedong-v3_5-0.0.1-SNAPSHOT.jar","port":8080}'
githubInstallationID: 63841363
