branch: main
buildConfig: '{"builder":"react","node_version":"20","build_dir":"/","build_commands":["npm run build"],"output_dir":"/dist","port":3000}'
containerPort: 3000
criticalService: false
domain: deep-report.xquare.app
githubInstallationID: 66550275
language: react
organization: dutexion
port: 3000
repository: deep-report
imageTag: f7badabcbd505b3cfcec101fc6c98e3f1952a16a
