apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: xquare-applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/team-xquare/xquare-gitops-repo-v3
        revision: HEAD
        files:
          - path: "club/*/*/*.values.yaml"
  template:
    metadata:
      name: '{{.path.segments.1}}-{{.path.basenameNormalized | trimSuffix ".values.yaml"}}'
      labels:
        club: "{{.path.segments.1}}"
        app: "{{.path.segments.2}}"
        env: '{{.path.basenameNormalized | trimSuffix ".values.yaml"}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/team-xquare/xquare-gitops-repo-v3
        targetRevision: HEAD
        path: templates/server
        helm:
          valueFiles:
            - "../../../{{.path.path}}"
          parameters:
            - name: club
              value: "{{.path.segments.1}}"
            - name: name
              value: "{{.path.segments.2}}"
            - name: environment
              value: '{{.path.basenameNormalized | trimSuffix ".values.yaml"}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.segments.1}}-{{.path.basenameNormalized | trimSuffix ".values.yaml"}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - PruneLast=true
