apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: xquare-gitops-repo-v3-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/team-xquare/xquare-gitops-repo-v3
        revision: HEAD
        files:
          - path: "club/*/*/*.values.yaml"
  template:
    metadata:
      name: '{{index .path.segments 1}}-{{.path.basenameNormalized | trimSuffix ".values.yaml"}}'
      labels:
        club: "{{index .path.segments 1}}"
        app: "{{index .path.segments 2}}"
        env: '{{.path.basenameNormalized | trimSuffix ".values.yaml"}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/team-xquare/xquare-gitops-repo-v3
        targetRevision: HEAD
        path: templates/server
        helm:
          valueFiles:
            - "../../../{{.path.path}}"
          parameters:
            - name: club
              value: "{{index .path.segments 1}}"
            - name: name
              value: "{{index .path.segments 2}}"
            - name: environment
              value: '{{.path.basenameNormalized | trimSuffix ".values.yaml"}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 1}}-{{.path.basenameNormalized | trimSuffix ".values.yaml"}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - PruneLast=true
