apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: xquare-club-infrastructure
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/team-xquare/xquare-gitops-repo-v3
        revision: HEAD
        directories:
          - path: "club/*"
  template:
    metadata:
      name: 'infrastructure-{{index .path.segments 1}}'
      labels:
        club: "{{index .path.segments 1}}"
        type: "infrastructure"
    spec:
      project: default
      source:
        repoURL: https://github.com/team-xquare/xquare-gitops-repo-v3
        targetRevision: HEAD
        path: templates/infrastructure
        plugin:
          name: argocd-vault-plugin-helm
          env:
            - name: HELM_ARGS
              value: >-
                --set club={{index .path.segments 1}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 1}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true