apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: xquare-club-infrastructure
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/team-xquare/xquare-gitops-repo-v3
        revision: HEAD
        directories:
          - path: "club/*"
  template:
    metadata:
      name: 'infrastructure-{{index .path.segments 1}}'
      labels:
        club: "{{index .path.segments 1}}"
        type: "infrastructure"
    spec:
      project: default
      source:
        repoURL: https://github.com/team-xquare/xquare-gitops-repo-v3
        targetRevision: HEAD
        path: templates/infrastructure
        plugin:
          name: argocd-vault-plugin-helm
          env:
            - name: HELM_ARGS
              value: >-
                --set club={{index .path.segments 1}}
                --set-json 'environments.stag=false'
                --set-json 'environments.prod=false'
                --post-renderer /bin/bash -c '
                  count_stag=$(find "club/{{index .path.segments 1}}" -name "stag.values.yaml" | wc -l);
                  count_prod=$(find "club/{{index .path.segments 1}}" -name "prod.values.yaml" | wc -l);
                  if [ "$count_stag" -gt 0 ]; then 
                    sed -i "s/environments.stag=false/environments.stag=true/g" $HELM_ARGS;
                  fi;
                  if [ "$count_prod" -gt 0 ]; then 
                    sed -i "s/environments.prod=false/environments.prod=true/g" $HELM_ARGS;
                  fi;
                  cat'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 1}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true