branch: develop
buildConfig: '{"builder":"vite","node_version":"22","build_dir":"/","build_commands":["nx run @entry-internship/entry-admin:build"],"output_dir":"/apps/entry-admin/dist","port":4200}'
containerPort: 4200
criticalService: false
domain: entry-recruit.xquare.app
githubInstallationID: 62368670
language: vite
organization: EntryDSM
port: 4200
repository: Entry-Internship
