branch: main
buildConfig: '{"node_version":"18","build_commands":["npm install"],"builder":"nodejs","build_dir":"/","command":"npm start","port":4000}'
containerPort: 4000
criticalService: false
domain: secret-game.xquare.app
githubInstallationID: 63879224
language: nodejs
organization: HyunSu1768
port: 4000
repository: secret
instanceType: x3.medium
imageTag: b0b1d29aef805c0dfd2a542d820fab189f16d6a2
