branch: main
buildConfig: '{"jdk_version":17,"output_dir":"/build/libs/Sillok_server-0.0.1-SNAPSHOT.jar","builder":"gradle","build_dir":".","build_commands":["./gradlew build -x test"], "port":8080}'
containerPort: 8080
criticalService: false
domain: sillok-api.xquare.app
githubInstallationID: 63841363
language: java
organization: Team-jeong-ho-kim
port: 8080
repository: Sillok_BE
imageTag: d50ca5b56ab9e8d6a9d8e673e059f21ca42a75d9
