branch: main
buildConfig: '{"jdk_version":17,"output_dir":"/build/libs/Sillok_server-0.0.1-SNAPSHOT.jar","builder":"gradle","build_dir":".","build_commands":["./gradlew build -x test"], "port":8080}'
containerPort: 8080
critical_service: false
domain: sillok-api.xquare.app
githubInstallationID: 63841363
language: java
organization: Team-jeong-ho-kim
port: 8080
repository: Sillok_BE
imageTag: 5cd52d1ad0b688506489f7b7054ba307d1fd9202
