{{- $fullname := (printf "%s-%s" .Values.name .Values.environment) }}
{{- $namespace := (printf "%s-%s" .Values.club .Values.environment) }}
{{- $ecrRegistry := "786584124104.dkr.ecr.ap-northeast-2.amazonaws.com" }}

{{- if .Values.imageTag }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ $namespace }}
  name: {{ $fullname }}
  labels:
    app.kubernetes.io/name: {{ $fullname }}
    app.kubernetes.io/part-of: {{ .Values.name }}
    app.kubernetes.io/environment: {{ .Values.environment }}
spec:
  {{- if eq .Values.criticalService true }}
  replicas: 2
  {{- else }}
  replicas: 1
  {{- end }}
  revisionHistoryLimit: 0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $fullname }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
        sidecar.istio.io/proxyCPU: "5m"
        sidecar.istio.io/proxyMemory: "128Mi"
        {{- if eq .Values.language "java" }}
        instrumentation.opentelemetry.io/inject-java: "true"
        {{- end }}
        {{- if eq .Values.language "nodejs" }}
        instrumentation.opentelemetry.io/inject-nodejs: "true"
        {{- end }}
      labels:
        app.kubernetes.io/name: {{ $fullname }}
        app.kubernetes.io/part-of: {{ .Values.name }}
    spec:
      serviceAccountName: {{ $namespace }}-vault-service-account
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - {{ $fullname }}
              topologyKey: "kubernetes.io/hostname"
      {{- if eq $fullname "project-secret-manager-be-prod" }}
      priorityClassName: system-cluster-critical
      {{- end }}
      nodeSelector:
        Karpenter: enabled
      {{- if eq .Values.criticalService true }}
      tolerations:
        - effect: "NoSchedule"
          key: xquare/criticalService
          operator: "Equal"
          value: "true"
      {{- else }}
      tolerations:
        - effect: "NoSchedule"
          key: xquare/server
          operator: "Equal"
          value: "true"
      {{- end }}
      terminationGracePeriodSeconds: 120
      containers:
        - name: {{ $fullname }}
          image: {{ $ecrRegistry }}/{{ $namespace }}/{{ .Values.name }}:{{ .Values.imageTag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.containerPort }}
          envFrom:
            - secretRef:
                name: {{ $fullname }}
                optional: true
          resources:
            requests:
              memory: "{{ if or (eq .Values.language "java") (eq .Values.language "nodejs") }}300Mi{{ else }}100Mi{{ end }}"
              cpu: "2m"
            limits:
              memory: "1Gi"
          readinessProbe:
            tcpSocket:
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 3
{{- end }}
