{{- $fullname := (printf "%s-%s" .Values.name .Values.environment) }}
{{- $namespace := (printf "%s-%s" .Values.club .Values.environment) }}

{{- if .Values.imageTag }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  namespace: {{ $namespace }}
  name: {{ $fullname }}
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $fullname }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ $fullname }}-vpa
  namespace: {{ $namespace }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ $fullname }}
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledResources: ["memory"]
{{- end }}
