branch: main
buildConfig: '{"builder":"react","node_version":"22","build_dir":"/","build_commands":["npm run build"],"output_dir":"/build","port":3000}'
containerPort: 3000
criticalService: false
domain: infra.xquare.app
githubInstallationID: 62433388
language: react
organization: team-xquare
repository: xquare-frontend-v2
imageTag: 7aec9f3b5b8a5f855c249e600c0b03c1aa1c7157
