organization: DaemaCoin
repository: deama_coin_backend
branch: main
containerPort: 3000
domain: daemacoin-server.xquare.app
language: nodejs
criticalService: false
buildConfig: '{"builder":"nodejs","node_version":"22.5.1","build_dir":"/","build_commands":["npm install && npm run build"],"output_dir":"/dist","port":3000}'
githubInstallationID: 63879080
imageTag: eba14f50d9f978a3cbe4b3da0040f669d8b40b9a
instanceType: x3.large
