organization: EntryDSM
repository: Equus-Status
branch: main
containerPort: 8080
domain: equus-status.xquare.app
language: java
criticalService: false
privateService: true
buildConfig: '{"builder":"gradle","jdk_version":17,"build_dir":".","build_commands":["./gradlew build -x test --build-cache"],"output_dir":"/build/libs/Equus-Status-0.0.0.jar","port":8080}'
githubInstallationID: 62368670
instanceType: x3.large
imageTag: latest
