organization: CuberLabs
repository: cuberpin-server
branch: main
containerPort: 8080
domain: cuberpin-server.xquare.app
criticalService: false
language: java
buildConfig: '{"jdk_version":17,"output_dir":"/build/libs/cuberpin-server-0.0.1-SNAPSHOT.jar","builder":"gradle","build_dir":"/","build_commands":["./gradlew build -x test"]}'
