branch: develop
buildConfig: '{"node_version":"22","build_commands":["npm install && npm run build"],"builder":"nodejs","build_dir":"/","command":"npm run start","port":3000}'
containerPort: 3000
criticalService: false
domain: keep-stag.xquare.app
githubInstallationID: 66778564
language: nodejs
organization: Keep-DSM
port: 3000
repository: keep-Backend
imageTag: 5ba4cc31a0cfb958844c905c64b408cf7a5c96cd
instanceType: x3.large
