organization: team-osj
repository: Lotura_BackEnd_V2
branch: main
containerPort: 3000
domain: lotura-prod.xquare.app
language: nodejs
criticalService: false
buildConfig: '{"builder":"nodejs","node_version":"22.5.1","build_dir":"/","build_commands":["yarn && yarn build"],"command":"yarn start","port":3000}'
githubInstallationID: 64110126
imageTag: 01e0a5f8db7155313526837af6edb0ae58ea3a44
instanceType: x3.medium
