---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "infrastructure.namespace" . }}
  labels:
    name: {{ include "infrastructure.namespace" . }}
    istio-injection: enabled

{{- if .Values.environments.stag }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "infrastructure.namespace" . }}-stag
  labels:
    name: {{ include "infrastructure.namespace" . }}-stag
    istio-injection: enabled
{{- end }}

{{- if .Values.environments.prod }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "infrastructure.namespace" . }}-prod
  labels:
    name: {{ include "infrastructure.namespace" . }}-prod
    istio-injection: enabled
{{- end }}