---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "infrastructure.namespace" . }}-prod
  labels:
    name: {{ include "infrastructure.namespace" . }}
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "infrastructure.namespace" . }}-stag
  labels:
    name: {{ include "infrastructure.namespace" . }}
    istio-injection: enabled
