{{- $fullname := (printf "%s-%s" .Values.name .Values.environment) }}
{{- $githubFullname := printf "%s_%s" .Values.name .Values.environment | lower }}
{{- $namespace := (printf "%s-%s" .Values.club .Values.environment) }}
{{- $githubAppID := 1172114 }}
{{- $githubPrivateKey := "<path:avp/data/github/ci-infrastructure#app_private_key>" }}
{{- $githubToken := "<path:avp/data/github/ci-infrastructure#token>" }}
{{- $ecrRegistry := "786584124104.dkr.ecr.ap-northeast-2.amazonaws.com" }}
{{- $argoEventsHost := "argo-events.xquare.app" }}
{{- $gitopsRepo := "team-xquare/xquare-gitops-repo-v3" }}
{{- $webhookPort := 12000 }}
{{- $useLatestTag := empty .Values.imageName }}
---
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: ci-eventbus
  namespace: {{ $namespace }}
spec:
  nats:
    native:
      replicas: 3 
      antiAffinity: false
      auth: none
      tolerations:
        - key: xquare/ci-server
          operator: Equal
          value: 'true'
          effect: NoSchedule
      containerTemplate:
        resources:
          requests:
            cpu: 15m
            memory: 25Mi
          limits:
            cpu: 40m
            memory: 50Mi
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: {{ $fullname }}-github-webhook
  namespace: {{ $namespace }}
spec:
  eventBusName: ci-eventbus
  github:
    {{ $githubFullname }}:
      active: true
      contentType: json
      events:
        - push
      githubApp:
        appID: {{ $githubAppID }}
        installationID: {{ .Values.githubInstallationID }}
        privateKey:
          key: privateKey.pem
          name: {{ $fullname }}-github-app-pem
      insecure: true
      repositories:
        - owner: {{ .Values.organization }}
          names:
            - {{ .Values.repository }}
      webhook:
        endpoint: /webhooks/{{ $fullname }}
        method: POST
        port: "{{ $webhookPort }}"
        url: "https://{{ $argoEventsHost }}"
  service:
    ports:
      - name: {{ $fullname }}
        port: {{ $webhookPort }}
        targetPort: {{ $webhookPort }}
  template:
    container:
      resources:
        requests:
          cpu: 25m
          memory: 40Mi
        limits:
          cpu: 60m
          memory: 75Mi    
    tolerations:
      - key: xquare/ci-server
        operator: Equal
        value: 'true'
        effect: NoSchedule
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: {{ $fullname }}-sensor
  namespace: {{ $namespace }}
spec:
  dependencies:
    - name: {{ $fullname }}-github-push
      eventName: {{ $githubFullname }}
      eventSourceName: {{ $fullname }}-github-webhook
      filters:
        data:
          - path: body.ref
            type: string
            value:
              - "refs/heads/{{ .Values.branch }}"
          {{- if $useLatestTag }}
          - path: body.X-GitHub-Event
            type: string
            value:
              - "ping"
          {{- end }}
        dataLogicalOperator: "or"
  eventBusName: ci-eventbus
  template:
    container:
      resources:
        requests:
          cpu: 25m
          memory: 40Mi
        limits:
          cpu: 60m
          memory: 75Mi
    serviceAccountName: {{ $fullname }}-workflow-sa
    tolerations:
      - key: xquare/ci-server
        operator: Equal
        value: 'true'
        effect: NoSchedule
  triggers:
    - retryStrategy:
        steps: 3
      template:
        k8s:
          operation: create
          {{- if not $useLatestTag }}
          parameters:
            - src:
                dependencyName: {{ $fullname }}-github-push
                dataKey: body.after
              dest: spec.arguments.parameters.0.value
          {{- end }}
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: {{ $fullname }}-ci-
                namespace: {{ $namespace }}
              spec:
                {{- if not $useLatestTag }}
                arguments:
                  parameters:
                    - name: git-sha
                {{- end }}
                entrypoint: ci-pipeline
                podGC:
                  strategy: OnPodCompletion
                serviceAccountName: {{ $fullname }}-workflow-sa
                templates:
                  - name: ci-pipeline
                    dag:
                      tasks:
                        - name: build
                          {{- if not $useLatestTag }}
                          arguments:
                            parameters:
                              - name: sha
                                value: "{{`{{workflow.parameters.git-sha}}`}}"
                          {{- end }}
                          template: docker-build
                        - name: update-gitops
                          arguments:
                            parameters:
                              - name: image-name
                                {{- if $useLatestTag }}
                                value: "{{ $ecrRegistry }}/{{ $namespace }}/{{ .Values.name }}:latest"
                                {{- else }}
                                value: "{{ $ecrRegistry }}/{{ $namespace }}/{{ .Values.name }}:{{`{{workflow.parameters.git-sha}}`}}"
                                {{- end }}
                          dependencies: [build]
                          template: update-gitops
                  
                  - name: docker-build
                    tolerations:
                      - key: xquare/ci-server
                        operator: Equal
                        value: 'true'
                        effect: NoSchedule
                    {{- if not $useLatestTag }}
                    inputs:
                      parameters:
                        - name: sha
                    {{- end }}
                    container:
                      image: gcr.io/kaniko-project/executor:latest
                      args:
                        - "--context=/workspace/repo"
                        - "--dockerfile=/workspace/repo/Dockerfile"
                        {{- if not $useLatestTag }}
                        - "--destination={{ $ecrRegistry }}/{{ $namespace }}/{{ .Values.name }}:{{`{{inputs.parameters.sha}}`}}"
                        {{- end }}
                        - "--destination={{ $ecrRegistry }}/{{ $namespace }}/{{ .Values.name }}:latest"
                        - "--cache=true"
                        - "--cache-repo={{ $ecrRegistry }}/cache"
                      env:
                        - name: AWS_SDK_LOAD_CONFIG
                          value: "true"
                      resources:
                        requests:
                          cpu: 80m
                          memory: 128Mi
                        limits:
                          cpu: 200m
                          memory: 256Mi
                      volumeMounts:
                        - name: workspace
                          mountPath: /workspace
                    initContainers:
                      - name: checkout-and-prepare
                        image: python:3.9-alpine
                        command: ["/bin/sh", "-c"]
                        args:
                          - |
                            apk add --no-cache git jq curl
                            pip install jinja2-cli

                            {{- if not $useLatestTag }}
                            SHA="{{`{{inputs.parameters.sha}}`}}"
                            {{- end }}
                            git clone -b {{ .Values.branch }} --single-branch https://github.com/{{ .Values.organization }}/{{ .Values.repository }}.git /workspace/repo
                            cd /workspace/repo
                              
                            {{- if not $useLatestTag }}
                              git checkout $SHA || { echo "Failed to checkout SHA: $SHA"; exit 1; }
                            {{- end }}

                            echo '{{ .Values.buildConfig }}' > /tmp/config.json
                            BUILDER=$(jq -r '.builder // "default"' /tmp/config.json)

                            curl -s "https://raw.githubusercontent.com/team-xquare/gitops-repo-v3/main/templates/dockerfile/templates/${BUILDER}.template" -o /tmp/template.j2 || echo "FROM alpine:latest" > /tmp/template.j2
                            jinja2 /tmp/template.j2 /tmp/config.json > /workspace/repo/Dockerfile
                        resources:
                          requests:
                            cpu: 40m
                            memory: 64Mi
                          limits:
                            cpu: 100m
                            memory: 128Mi
                        volumeMounts:
                          - name: workspace
                            mountPath: /workspace
                  
                  - name: update-gitops
                    tolerations:
                      - key: xquare/ci-server
                        operator: Equal
                        value: 'true'
                        effect: NoSchedule
                    inputs:
                      parameters:
                        - name: image-name
                    container:
                      image: bitnami/git:latest
                      command: [sh, -c]
                      args:
                        - |
                          curl -X POST \
                            -H "Authorization: token ${GITHUB_TOKEN}" \
                            -H "Accept: application/vnd.github.v3+json" \
                            https://api.github.com/repos/{{ $gitopsRepo }}/dispatches \
                            -d '{
                              "event_type": "config-api",
                              "client_payload": {
                                "path": "{{ .Values.club }}/{{ .Values.name }}/{{ .Values.environment }}",
                                "action": "apply",
                                "spec": {
                                  "image_name": "'"{{`{{inputs.parameters.image-name}}`}}"'"
                                }
                              }
                            }'
                      env:
                        - name: GITHUB_TOKEN
                          valueFrom:
                            secretKeyRef:
                              key: token
                              name: {{ $fullname }}-github-token
                      resources:
                        requests:
                          cpu: 15m
                          memory: 25Mi
                        limits:
                          cpu: 40m
                          memory: 50Mi
                volumes:
                  - name: workspace
                    emptyDir: {}
        name: {{ $fullname }}-workflow-trigger
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullname }}-github-webhook-vs
  namespace: {{ $namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ $argoEventsHost }}
spec:
  hosts:
    - "{{ $argoEventsHost }}"
  gateways:
    - istio-system/xquare-ingressgateway
  http:
    - match:
        - uri:
            prefix: /webhooks/{{ $fullname }}
      route:
        - destination:
            host: {{ $fullname }}-github-webhook-eventsource-svc
            port:
              number: {{ $webhookPort }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullname }}-workflow-sa
  namespace: {{ $namespace }}
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::786584124104:role/kaniko-ecr-push-role"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $fullname }}-workflow-role
  namespace: {{ $namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "watch", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflows", "workflows/finalizers"]
    verbs: ["get", "list", "watch", "update", "patch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $fullname }}-workflow-rolebinding
  namespace: {{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $fullname }}-workflow-role
subjects:
  - kind: ServiceAccount
    name: {{ $fullname }}-workflow-sa
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-github-app-pem
  namespace: {{ $namespace }}
type: Opaque
data:
  privateKey.pem: "{{ $githubPrivateKey | b64enc }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-github-token
  namespace: {{ $namespace }}
type: Opaque
data:
  token: "{{ $githubToken | b64enc }}"