{{- $namespace := (printf "%s-%s" .Values.club .Values.environment) }}
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: otel-instrumentation-{{ $.Values.club }}-{{ $.Values.environment }}
  namespace: {{ $namespace }}
spec:
  signals:
    - traces
    - metrics
    - logs
  exporter:
    endpoint: "http://0.0.0.0:4317"
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
