{{- $fullname := (printf "%s-%s" .Values.name .Values.environment) }}
{{- $namespace := (printf "%s-%s" .Values.club .Values.environment) }}

apiVersion: v1
kind: Service
metadata:
  namespace: {{ $namespace }}
  name: {{ $fullname }}
  labels:
    app.kubernetes.io/name: {{ $fullname }}
    app.kubernetes.io/part-of: {{ .Values.name }}
    app.kubernetes.io/environment: {{ .Values.environment }}
spec:
  type: {{ if eq .Values.name "mozu-server" }}NodePort{{ else }}ClusterIP{{ end }}
  selector:
    app.kubernetes.io/name: {{ $fullname }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
    - name: port
      port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
    {{- if eq $fullname "xquare-infra-prod" }}
    - name: otel-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    {{- end }}
