{{- $fullname := (printf "%s-%s" .Values.name .Values.environment) }}
{{- $namespace := (printf "%s-%s" .Values.club .Values.environment) }}
{{- if .Values.imageName }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ $fullname }}-vpa
  namespace: {{ $namespace }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ $fullname }}
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledResources: ["memory"]
{{- end }}